### ISSUE TITLE
Truncations after tag boundary

### ISSUE THREAD

**Issue by eat-multi** [nono/HTML-Truncator#15]
For html like the following:
```html
<p>
  five words in this paragraph
</p>
<p>
  some more text which will be truncated
</p>
```

Given the above html is stored in the `html` var:
```ruby
HTML_Truncator.truncate(html, 5)
```

returns html as follows:
```html
<p>
  five words in this paragraph
</p>
<p>
  ...
</p>
```

Ideally I would expect the `...` to be appended to the first `<p>` block, with the second block removed, like so:
```html
<p>
  five words in this paragraph...
</p>
```

This looks like it could be a little bit of a pain to implement, sorry :3

**Comment by nono** [comment]
Hello,

thanks for your suggestion.

In my mind, the first paragraph is complete so the `...` belongs to the second paragraph. Can you explain me why you think the ellipsis in the first paragraph is better?

**Comment by eat-multi** [comment]
I don't think I thought this through properly. What I suggested above would actually be really *wrong* behaviour.

I think an ellipsis at the start of (and replacing) a paragraph isn't a common construct in writing, hence looking a little wrong to me when rendered. I'm happy for this to be closed. Thank you for the gem.

-------------------------
If I want to avoid having `<p>...</p>` appearing occasionally (from an aesthetic perspective) I can just write a little wrapper that tries to avoid truncating at block boundaries giving:
`<p>five words in this...</p>`

**Comment by nono** [comment]
OK :)
