### ISSUE TITLE
For speed, allow Nokogiri nodes to be passed in

### ISSUE THREAD

**Issue by jtsay362** [nono/HTML-Truncator#19]
I am already using Nokogiri for processing HTML, and it would be more efficient if I could just pass in a node to your sanitizer, instead of outputting to HTML, then having your library re-convert it to a node.

**Comment by nono** [comment]
It's a good idea. It's possible and I have added an example on how to do that: https://github.com/nono/HTML-Truncator/commit/e7dfff5c0236ea8b70a8f3827353c9b2eca8bd1a

**Comment by jtsay362** [comment]
Nice, thanks!

**Comment by gerwitz** [comment]
It's surprising that the .truncate method returns an array
