### ISSUE TITLE
Pattern in words scan

### ISSUE THREAD

**Issue by micleclickme** [nono/HTML-Truncator#21]
To search words and count in text node you use pattern like this 
https://github.com/nono/HTML-Truncator/blob/45382ea67c5cebd141863ab5a2f76e4a5fc5b727/lib/html_truncator.rb#L78
but it doesn't covers special charecters like NO-BREAK SPACE
I think pattern /[[:space:]]*[[[:punct:]][[:word:]]]+/ is better because also covers non-ASCII characters in utf-8

**Comment by nono** [comment]
Hello, it looks like a good idea. Can you make a pull request with this change?
